### ISSUE TITLE
cmake . fails on MacOS (Ventura 13.5)

### ISSUE THREAD

**Issue by gasparschott** [ScanTailor-Advanced/scantailor-libs-build#14] opened 2023-08-22 19:17 UTC
CMake Error at core/CMakeLists.txt:140 (translation_sources):
  Unknown CMake command "translation_sources".

**Comment by ghost** [comment] 2023-08-28 16:01
Hello @gasparschott 

The build instructions are designed for Windows or Linux only, building for macOS is still not integrated into the guide, see issue #3 for more details.

**Comment by ghost** [comment] 2023-08-28 16:01
Duplicate of #3

**Closed as not planned** 2023-08-28 16:01 UTC
Labels: question

**Comment by mara004** [comment] 2023-08-28 18:00
(formerly) @lightsilverberryfox did you just delete your account or something?
